---
Driver:
  headless: true
  type: chrome
  window_width: 1920
  window_height: 1080
  # version: auto (managed by webdriver-manager)

VisualTests:
  enabled: true
  fail: true
  save: false
  baseline_name: "base"
