---
name: Lint - Super-Linter

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: 🧹 Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: 🧹 Lint Codebase
        uses: carlos-camara/qa-hub-actions/lint-codebase@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: ${{ github.event.repository.default_branch }}
